spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ktp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: l20020204
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /
